'use client';
import {useEffect,useRef,useState} from 'react';
import Paper from '@/components/Paper';
import AiBar from '@/components/AiBar';
import {SECTIONS,LISTS,blank,keywordGaps} from '@/lib/resume';

export default function BuilderWorkspace(){
 const[store,setStore]=useState(null),[toast,setToast]=useState(''),[dlg,setDlg]=useState(null),[job,setJob]=useState(''),[gaps,setGaps]=useState(null),[dark,setDark]=useState(false);
 const drag=useRef(null),tt=useRef();
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem('rs-next'));if(s?.list?.length){const list=s.list.map(r=>({...r,order:[...(r.order||[]),...Object.keys(SECTIONS).filter(k=>!(r.order||[]).includes(k))],hidden:r.hidden||{},certifications:r.certifications||[],languages:r.languages||[],achievements:r.achievements||[],custom:r.custom||[]}));setStore({...s,list});}else throw 0}catch{const b=blank();setStore({cur:b.id,list:[b],hist:{}})}
    const preference=localStorage.getItem('Lily-theme');const legacy=localStorage.getItem('rs-dark');const systemDark=matchMedia('(prefers-color-scheme:dark)').matches;const isDark=preference?preference==='Dark'||preference==='System'&&systemDark:legacy?legacy==='1':systemDark;setDark(isDark)},[]);
 useEffect(()=>{if(store)localStorage.setItem('rs-next',JSON.stringify(store))},[store]);
 useEffect(()=>{document.documentElement.classList.toggle('dark',dark);try{localStorage.setItem('rs-dark',dark?'1':'0')}catch{}},[dark]);
 if(!store)return<div className="p-8"><div className="skel w-1/3"/><div className="skel w-1/2"/></div>;
 const R=store.list.find(r=>r.id===store.cur)||store.list[0];
 const notify=m=>{setToast(m);clearTimeout(tt.current);tt.current=setTimeout(()=>setToast(''),2200)};
 const edit=fn=>setStore(s=>({...s,list:s.list.map(r=>r.id===s.cur?fn(structuredClone(r)):r)}));
 const snap=()=>setStore(s=>{const cur=s.list.find(r=>r.id===s.cur);return{...s,hist:{...s.hist,[s.cur]:[{t:new Date().toLocaleString(),d:cur},...(s.hist[s.cur]||[])].slice(0,10)}}});
 const accept=(set)=>{snap();edit(set)};
 const setKey=(k,v)=>edit(r=>{r[k]=v;return r});
 const setItem=(k,j,f,v)=>edit(r=>{r[k][j][f]=v;return r});
 const move=(k,dir)=>edit(r=>{const i=r.order.indexOf(k),j=i+dir;if(j>=0&&j<r.order.length)[r.order[i],r.order[j]]=[r.order[j],r.order[i]];return r});
 const drop=to=>{const from=drag.current;if(!from||from===to)return;edit(r=>{r.order.splice(r.order.indexOf(from),1);r.order.splice(r.order.indexOf(to),0,from);return r});drag.current=null};
 const go=id=>setStore(s=>({...s,cur:id}));
 const glow=e=>{const b=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--mx',e.clientX-b.left+'px');e.currentTarget.style.setProperty('--my',e.clientY-b.top+'px')};

 return(<div className="builder-page">
 <header className="builder-header">
  <a href="/dashboard" className="brand-lockup"><span className="brand-mark">R</span><span>Resume Studio</span></a>
  <div className="builder-title"><span className="eyebrow">RESUME EDITOR</span><input aria-label="Resume name" value={R.name} onChange={e=>setKey('name',e.target.value)}/><span className="save-state"><span/> All changes saved</span></div>
  <nav className="builder-actions" aria-label="Editor actions">
   <button className="quiet-button" onClick={()=>setDlg('lib')}>My resumes</button>
   <button className="quiet-button" onClick={()=>setDlg('ver')}>History</button>
    <button className="quiet-button icon-button" aria-label="Toggle theme" onClick={()=>{const next=!dark;setDark(next);localStorage.setItem('Lily-theme',next?'Dark':'Light')}}>◐</button>
   <button className="primary-button" onClick={()=>{notify('Choose “Save as PDF” in the print dialog');setTimeout(print,400)}}>Export PDF <span>↗</span></button>
  </nav>
 </header>
 <main className="builder-layout">
  <section className="builder-editor" aria-label="Resume editor">
   <div className="editor-heading"><div><span className="eyebrow">YOUR STORY, REFINED</span><h1>Build your resume</h1></div><button className="quiet-button" onClick={()=>setDlg('lib')}>Switch resume</button></div>
   <div className="builder-template-row"><label>Template <select aria-label="Template" className="editor-select" value={R.template} onChange={e=>setKey('template',e.target.value)}><option value="modern">Modern</option><option value="classic">Classic</option><option value="minimal">Minimal</option></select></label><label>Accent <input aria-label="Accent colour" type="color" value={R.color} onChange={e=>setKey('color',e.target.value)}/></label><label>Typeface <select aria-label="Font" className="editor-select" value={R.font} onChange={e=>setKey('font',e.target.value)}>{['Inter','Lora','DM Sans','Fraunces'].map(f=><option key={f}>{f}</option>)}</select></label></div>
   <div className="editor-section"><div className="section-title"><div><span className="eyebrow">01 / START HERE</span><h2>Personal details</h2></div><span className="complete-pill">●  In progress</span></div><div className="form-grid">{[['fullName','Full name'],['title','Professional title'],['email','Email address'],['phone','Phone number']].map(([k,l])=><label key={k}>{l}<input className="studio-input" aria-label={l} value={R[k]} onChange={e=>setKey(k,e.target.value)}/></label>)}</div><label className="full-field">Location<input className="studio-input" aria-label="Location" value={R.location} onChange={e=>setKey('location',e.target.value)}/></label></div>
   <div className="editor-section"><div className="section-title"><div><span className="eyebrow">OPTIONAL</span><h2>Target a role</h2></div></div><textarea className="studio-input studio-textarea" placeholder="Paste a job description to find relevant keywords" value={job} onChange={e=>setJob(e.target.value)}/><button className="text-button" onClick={()=>job.trim()?setGaps(keywordGaps(job,R)):notify('Paste a job description first')}>Find keyword gaps <span>→</span></button>{gaps&&<p className="feedback-copy">{gaps.length?<>Keywords in the job description: <b>{gaps.join(', ')}</b>. Add them only if they reflect your experience.</>:'No obvious keyword gaps found.'}</p>}</div>
   {R.order.map((k,i)=><details key={k} open className="editor-section collapsible-section" onDragOver={e=>e.preventDefault()} onDrop={()=>drop(k)}><summary className="section-title"><div className="section-index"><span className="eyebrow">0{i+2} / SECTION</span><h2>{SECTIONS[k]}</h2></div><span className="section-controls"><span draggable onDragStart={()=>drag.current=k} onClick={e=>e.preventDefault()} className="drag-handle" title="Drag to reorder" aria-hidden>⠿</span><button className="mini-button" aria-label="Move section up" onClick={e=>{e.preventDefault();move(k,-1)}}>↑</button><button className="mini-button" aria-label="Move section down" onClick={e=>{e.preventDefault();move(k,1)}}>↓</button><button className="visibility-button" onClick={e=>{e.preventDefault();edit(r=>{r.hidden[k]=!r.hidden[k];return r})}}>{R.hidden[k]?'Show':'Hide'}</button></span></summary>
    {(k==='summary'||k==='skills')&&<><textarea className="studio-input studio-textarea" aria-label={SECTIONS[k]} value={R[k]} placeholder={k==='summary'?'A concise introduction to your experience and strengths':'Add skills separated by commas'} onChange={e=>setKey(k,e.target.value)}/><AiBar text={R[k]} job={job} notify={notify} onAccept={t=>accept(r=>{r[k]=t;return r})}/></>}
    {LISTS[k]&&<>{R[k].map((x,j)=><div key={j} className="resume-entry"><div className="form-grid"><input className="studio-input" placeholder={LISTS[k][0]} aria-label={LISTS[k][0]} value={x.a} onChange={e=>setItem(k,j,'a',e.target.value)}/><input className="studio-input" placeholder={LISTS[k][1]} aria-label={LISTS[k][1]} value={x.b} onChange={e=>setItem(k,j,'b',e.target.value)}/></div><input className="studio-input" placeholder={LISTS[k][2]} aria-label={LISTS[k][2]} value={x.c} onChange={e=>setItem(k,j,'c',e.target.value)}/><textarea className="studio-input studio-textarea" placeholder="What did you do? Plain facts are fine." value={x.text} onChange={e=>setItem(k,j,'text',e.target.value)}/><AiBar text={x.text} job={job} notify={notify} onAccept={t=>accept(r=>{r[k][j].text=t;return r})}/><button className="text-button danger-text" onClick={()=>edit(r=>{r[k].splice(j,1);return r})}>Remove entry</button></div>)}<button className="add-entry" onClick={()=>edit(r=>{r[k].push({a:'',b:'',c:'',text:''});return r})}>＋ Add {SECTIONS[k].toLowerCase()}</button></>}
   </details>)}
  </section>
  <aside className="resume-preview-panel" onPointerMove={glow}><div className="preview-toolbar"><span><span className="status-dot"/> LIVE PREVIEW</span><button className="text-button" onClick={()=>notify('Preview is up to date')}>Fit to screen</button></div><Paper r={R}/><div className="preview-caption">A4 · 1 page · ATS-friendly layout</div></aside>
 </main>
 {dlg&&<div className="studio-overlay" onClick={()=>setDlg(null)}><div role="dialog" aria-modal="true" aria-label={dlg==='lib'?'My resumes':'Version history'} className="studio-dialog" onClick={e=>e.stopPropagation()}>{dlg==='lib'?<><span className="eyebrow">YOUR WORKSPACE</span><h3>My resumes</h3>{store.list.map(r=><div key={r.id} className="resume-library-row"><button className="mini-button" aria-label="Favourite" onClick={()=>setStore(s=>({...s,list:s.list.map(x=>x.id===r.id?{...x,fav:!x.fav}:x)}))}>{r.fav?'★':'☆'}</button><input className="studio-input" value={r.name} aria-label="Rename resume" onChange={e=>setStore(s=>({...s,list:s.list.map(x=>x.id===r.id?{...x,name:e.target.value}:x)}))}/><button className="quiet-button" onClick={()=>{go(r.id);setDlg(null)}}>Open</button><button className="mini-button" aria-label="Duplicate" onClick={()=>setStore(s=>({...s,list:[...s.list,{...structuredClone(r),id:String(Date.now()),name:r.name+' (copy)'}]}))}>⧉</button><button className="mini-button" aria-label="Delete" onClick={()=>store.list.length<2?notify('Keep at least one resume'):setStore(s=>{const list=s.list.filter(x=>x.id!==r.id);return{...s,list,cur:s.cur===r.id?list[0].id:s.cur}})}>×</button></div>)}<button className="primary-button" onClick={()=>{const b=blank();setStore(s=>({...s,list:[...s.list,b],cur:b.id}));setDlg(null);notify('New resume created')}}>＋ New resume</button></>:<><span className="eyebrow">VERSION HISTORY</span><h3>Restore a previous version</h3>{(store.hist[R.id]||[]).length?store.hist[R.id].map((v,i)=><div key={i} className="history-row"><span>{v.t}</span><button className="quiet-button" onClick={()=>{edit(()=>({...v.d}));setDlg(null);notify('Version restored')}}>Restore</button></div>):<p className="feedback-copy">A version is saved each time you accept an AI change.</p>}</>}<button className="quiet-button dialog-close" onClick={()=>setDlg(null)}>Close</button></div></div>}
 <div role="status" className={`studio-toast ${toast?'visible':''}`}>{toast}</div>
 </div>)}
