"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.aiRouter = void 0;
const express_1 = require("express");
const ai_controller_1 = require("../controllers/ai.controller");
const ai_rate_limit_middleware_1 = require("../middleware/ai-rate-limit.middleware");
const auth_middleware_1 = require("../middleware/auth.middleware");
const ai_usage_limit_middleware_1 = require("../middleware/ai-usage-limit.middleware");
const require_plan_middleware_1 = require("../middleware/require-plan.middleware");
const validate_body_1 = require("../middleware/validate-body");
const ai_validator_1 = require("../validators/ai.validator");
exports.aiRouter = (0, express_1.Router)();
exports.aiRouter.use(auth_middleware_1.authMiddleware, ai_rate_limit_middleware_1.aiRateLimit, ai_usage_limit_middleware_1.aiUsageLimit);
exports.aiRouter.post('/generate', (0, validate_body_1.validateBody)(ai_validator_1.generateSchema), ai_controller_1.generate);
exports.aiRouter.post('/improve', (0, validate_body_1.validateBody)(ai_validator_1.improveSchema), ai_controller_1.improve);
exports.aiRouter.post('/suggestions', (0, validate_body_1.validateBody)(ai_validator_1.suggestionsSchema), ai_controller_1.suggestions);
exports.aiRouter.post('/chat', (0, validate_body_1.validateBody)(ai_validator_1.chatSchema), ai_controller_1.chat);
exports.aiRouter.post('/analyze-resume', (0, validate_body_1.validateBody)(ai_validator_1.analyzeResumeSchema), ai_controller_1.analyzeResume);
exports.aiRouter.post('/tailor', (0, require_plan_middleware_1.requirePlan)('PREMIUM'), (0, validate_body_1.validateBody)(ai_validator_1.tailorSchema), ai_controller_1.tailor);
