"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.apiRouter = void 0;
const express_1 = require("express");
const health_controller_1 = require("../controllers/health.controller");
const auth_routes_1 = require("./auth.routes");
const ai_routes_1 = require("./ai.routes");
const jobs_routes_1 = require("./jobs.routes");
const resumes_routes_1 = require("./resumes.routes");
const templates_routes_1 = require("./templates.routes");
const subscription_routes_1 = require("./subscription.routes");
const admin_routes_1 = require("./admin.routes");
const users_routes_1 = require("./users.routes");
exports.apiRouter = (0, express_1.Router)();
exports.apiRouter.get('/health', health_controller_1.health);
exports.apiRouter.use('/auth', auth_routes_1.authRouter);
exports.apiRouter.use('/ai', ai_routes_1.aiRouter);
exports.apiRouter.use('/jobs', jobs_routes_1.jobsRouter);
exports.apiRouter.use('/templates', templates_routes_1.templatesRouter);
exports.apiRouter.use('/resumes', resumes_routes_1.resumesRouter);
exports.apiRouter.use('/users', users_routes_1.usersRouter);
exports.apiRouter.use('/subscription', subscription_routes_1.subscriptionRouter);
exports.apiRouter.use('/admin', admin_routes_1.adminRouter);
