"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.resumesRouter = void 0;
const express_1 = require("express");
const resume_analysis_controller_1 = require("../controllers/resume-analysis.controller");
const resumes_controller_1 = require("../controllers/resumes.controller");
const auth_middleware_1 = require("../middleware/auth.middleware");
const premium_template_middleware_1 = require("../middleware/premium-template.middleware");
const validate_body_1 = require("../middleware/validate-body");
const resume_validator_1 = require("../validators/resume.validator");
exports.resumesRouter = (0, express_1.Router)();
exports.resumesRouter.use(auth_middleware_1.authMiddleware);
exports.resumesRouter.get('/', resumes_controller_1.listResumes);
exports.resumesRouter.post('/', (0, validate_body_1.validateBody)(resume_validator_1.resumeCreateSchema), premium_template_middleware_1.premiumTemplateMiddleware, resumes_controller_1.createResume);
exports.resumesRouter.get('/:id/versions', resumes_controller_1.listResumeVersions);
exports.resumesRouter.post('/:id/versions/:versionId/restore', resumes_controller_1.restoreResumeVersion);
exports.resumesRouter.post('/:id/export/pdf', resumes_controller_1.exportResume);
exports.resumesRouter.get('/:id/analysis', resume_analysis_controller_1.getResumeAnalysisHistory);
exports.resumesRouter.get('/:id', resumes_controller_1.getResume);
exports.resumesRouter.put('/:id', (0, validate_body_1.validateBody)(resume_validator_1.resumeUpdateSchema), premium_template_middleware_1.premiumTemplateMiddleware, resumes_controller_1.updateResume);
exports.resumesRouter.delete('/:id', resumes_controller_1.deleteResume);
