"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.templatesRouter = void 0;
const express_1 = require("express");
const templates_controller_1 = require("../controllers/templates.controller");
const ai_rate_limit_middleware_1 = require("../middleware/ai-rate-limit.middleware");
const admin_middleware_1 = require("../middleware/admin.middleware");
const auth_middleware_1 = require("../middleware/auth.middleware");
const ai_usage_limit_middleware_1 = require("../middleware/ai-usage-limit.middleware");
const optional_auth_middleware_1 = require("../middleware/optional-auth.middleware");
const validate_body_1 = require("../middleware/validate-body");
const template_validator_1 = require("../validators/template.validator");
exports.templatesRouter = (0, express_1.Router)();
exports.templatesRouter.get('/', optional_auth_middleware_1.optionalAuthMiddleware, templates_controller_1.listTemplates);
exports.templatesRouter.get('/category/:category', optional_auth_middleware_1.optionalAuthMiddleware, templates_controller_1.listTemplatesByCategory);
exports.templatesRouter.get('/:id', optional_auth_middleware_1.optionalAuthMiddleware, templates_controller_1.getTemplate);
exports.templatesRouter.post('/generate-concept', auth_middleware_1.authMiddleware, ai_rate_limit_middleware_1.aiRateLimit, ai_usage_limit_middleware_1.aiUsageLimit, (0, validate_body_1.validateBody)(template_validator_1.generateTemplateConceptSchema), templates_controller_1.generateTemplateConcept);
exports.templatesRouter.post('/', auth_middleware_1.authMiddleware, admin_middleware_1.adminMiddleware, (0, validate_body_1.validateBody)(template_validator_1.templateCreateSchema), templates_controller_1.createTemplate);
exports.templatesRouter.put('/:id', auth_middleware_1.authMiddleware, admin_middleware_1.adminMiddleware, (0, validate_body_1.validateBody)(template_validator_1.templateUpdateSchema), templates_controller_1.updateTemplate);
exports.templatesRouter.delete('/:id', auth_middleware_1.authMiddleware, admin_middleware_1.adminMiddleware, templates_controller_1.deleteTemplate);
