"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.usersRouter = void 0;
const express_1 = require("express");
const users_controller_1 = require("../controllers/users.controller");
const auth_middleware_1 = require("../middleware/auth.middleware");
const validate_body_1 = require("../middleware/validate-body");
const auth_validator_1 = require("../validators/auth.validator");
const auth_rate_limit_middleware_1 = require("../middleware/auth-rate-limit.middleware");
exports.usersRouter = (0, express_1.Router)();
exports.usersRouter.patch('/me', auth_middleware_1.authMiddleware, (0, validate_body_1.validateBody)(auth_validator_1.profileUpdateSchema), users_controller_1.updateCurrentUser);
exports.usersRouter.get('/profile', auth_middleware_1.authMiddleware, users_controller_1.getProfile);
exports.usersRouter.put('/profile', auth_middleware_1.authMiddleware, (0, validate_body_1.validateBody)(auth_validator_1.profileDetailsSchema), users_controller_1.updateProfile);
exports.usersRouter.patch('/password', auth_rate_limit_middleware_1.authRateLimit, auth_middleware_1.authMiddleware, (0, validate_body_1.validateBody)(auth_validator_1.passwordChangeSchema), users_controller_1.changePassword);
exports.usersRouter.patch('/settings', auth_middleware_1.authMiddleware, (0, validate_body_1.validateBody)(auth_validator_1.userSettingsSchema), users_controller_1.updateSettings);
